[workspace]
resolver = "2"
members = [
  "bootstrap",
  "controller",
  "debug_web",
  "monitor",
  "tailscale",
  "trader",
  "trading",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1